### ISSUE TITLE
grey window in screenpipe

### ISSUE THREAD

**Issue by liber145** [fmirus/torcs-1.3.7#1]
It is very cool! I had a hard time install torcs scrserver on version 1.3.4. This repository helps me a lot to install the latest version. Well, I still meet some problems. 
Commands that I used after installation:
```bash
$ torcs 
```
The race GUI came out.
```bash
$ cd torcs-1.3.7/screenpipe
./IPC_command
```
A grey window named "Image from TORCS" came out. It remains grey after pressing "P" several times.
```bash
$ python screenpipe_client.py
Connecting to server ...
```
The window "Image from TORCS" is still grey after pressing "P" several times.

Could you tell me how to get the image during the racing time?

**Comment by fmirus** [comment]
Hi @liber145 

the screenpipe-directory is a leftover from a previous implementation, that I am not using anymore. However, my repo [torcs_ros](https://github.com/fmirus/torcs_ros) might be interesting for you. It holds a (imho) nice implementation for interfacng TORCS with [ROS](http://www.ros.org/). Using it, you can publish not only the current game image, but also all other sensors provided from the scr-server into the ROS-system and use them in your (C++ or python) ROS-nodes for driving. 

I hope this helps.

**Comment by liber145** [comment]
@fmirus Thanks a lot! I will have a try this weekend. :)

**Comment by fmirus** [comment]
@liber145 Have you already tried [torcs_ros](https://github.com/fmirus/torcs_ros)? Was it helpful for your  needs? If yes, can I close this issue? Thanks :)

**Comment by liber145** [comment]
Sorry for the delay. Recently I am busy with some other projects. I can only turn to torcs after that. Thanks for your response! Let's close this issue.
