### ISSUE TITLE
How to obtain the current image?

### ISSUE THREAD

**Issue by Aarnnity** [fmirus/torcs-1.3.7#7]
Hello, I’m a novice, I saw about your project on GitHub, I think it’s very cool. However, I have encountered some problems, such as: how to obtain the current image in Torcs. Can you please provide some help, thank you.

**Comment by fmirus** [comment]
Hi @Aarnnity, thank you for creating this issue and for your interest in this repository and sorry for my late reply. The easiest way to obtain the current image from TORCS is by using the  [interface to ROS](https://github.com/fmirus/torcs_ros) but you can obtain it without ROS as well. However, it is hard to provide help without knowing your setup such as what version of Ubuntu you are using etc.

**Comment by Aarnnity** [comment]
> Hi @Aarnnity, thank you for creating this issue and for your interest in this repository and sorry for my late reply. The easiest way to obtain the current image from TORCS is by using the [interface to ROS](https://github.com/fmirus/torcs_ros) but you can obtain it without ROS as well. However, it is hard to provide help without knowing your setup such as what version of Ubuntu you are using etc.

Hello, I installed torcs in Ubuntu 16.04. Solved the problem of image acquisition by viewing this URL https://github.com/yanpanlau/DDPG-Keras-Torcs. Recently, I want to train DDPG on multiple lanes, but the added other vehicles are always easy to send collisions, so I want to modify the properties of other vehicles, such as their speed. But there has been no progress. Do you know anything about this?
