### ISSUE TITLE
modify the properties of other vehicles.

### ISSUE THREAD

**Issue by Aarnnity** [fmirus/torcs-1.3.7#8]
Hi,
I installed torcs in Ubuntu 16.04. Recently, I want to train DDPG on multiple lanes, but the added other vehicles are always easy to send collisions, so I want to modify the properties of other vehicles, such as their speed. But there has been no progress. Do you know anything about this?

**Comment by fmirus** [comment]
Hi @Aarnnity ,
there are plenty of AI-drivers ready to use TORCS already comes with, please check out the folder 
```
torcs-1.3.7/src/drivers
```
If those drivers are not able to do what you want them to do, you can implement additional drivers yourself. There is a robot tutorial available [here](http://www.berniw.org/tutorials/robot/tutorial.html). Although this tutorial targets an older version of TORCS, it should work fine with version 1.3.7 as well. Furthermore, you could also use the ```scr_server``` to implement very simple drivers in Python for instance. Hence, I do not think that this is really an issue of the current code-base. Therefore, closing this issue.

**Comment by Aarnnity** [comment]
> Hi @Aarnnity ,
> there are plenty of AI-drivers ready to use TORCS already comes with, please check out the folder
> 
> ```
> torcs-1.3.7/src/drivers
> ```
> 
> If those drivers are not able to do what you want them to do, you can implement additional drivers yourself. There is a robot tutorial available [here](http://www.berniw.org/tutorials/robot/tutorial.html). Although this tutorial targets an older version of TORCS, it should work fine with version 1.3.7 as well. Furthermore, you could also use the `scr_server` to implement very simple drivers in Python for instance. Hence, I do not think that this is really an issue of the current code-base. Therefore, closing this issue.

okey, thank you!
